### ISSUE TITLE
Currency doesn't change

### ISSUE THREAD

**Issue by danielgheoltan** [siment/St_ProductListBlockCache#1]
Hello,

I changed the currency and it shows the previous one that was cached. Can you fix this please?

Thanks

**Comment by siment** [comment]
Thank you for raising the issue. I will be looking into this shortly

**Comment by siment** [comment]
@danielgheoltan this should be fixed in 25019d993fef2495a12257b6f6cdd853d76d7c2a. I only tested language switcher but it follows the same principle as currency switcher.

**Comment by danielgheoltan** [comment]
Thanks! :+1:
